# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 120f5814adc919575be349d68cb9f72ed17b1db15c637df5af19689f98aed62f1b5c43134b6edf07457cdb7eb31650e540bebd67ce9a8198cdb1ed84603ed240

test:
  secret_key_base: 2427b0a3f518a2b7c1da3886f191e5216d1eae3fd7cfa5b03cff2999066ec33ae6ae4e570e94f65cf6129655b6be1c8f8ba5a404a91adda57e7ca15dfd671601

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
